language: node_js
node_js:
  - '10.15'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master
    - develop

#before_script:
#  - google-chrome --version
#  - npm install -g @angular/cli
#  - npm install webdriver-manager -g
#  - webdriver-manager update
#  - webdriver-manager start > ./webdriver.log 2>&1 &

script:
#  - npm run lint
#  - npm run lint-css
#  - ng test --watch=false --browsers=ChromeHeadlessNoSandbox --code-coverage=true
#  - ng e2e
  - echo "Test"

#notifications:
#  email:
#    on_failure: change
#    on_success: change

after_failure:
  - cat ./webdriver.log

#after_script:
#  - npm install ocular.js
#  - "$(npm bin)/ocular coverage/clover.xml"
after_success:
  - openssl aes-256-cbc -K $encrypted_9a6207bd2a44_key -iv $encrypted_9a6207bd2a44_iv -in geekhub-deployment.enc -out geekhub-deployment -d
  - rm geekhub-deployment.enc # Don't need it anymore
  - chmod 600 geekhub-deployment
  - mv geekhub-deployment ~/.ssh/id_rsa
  - if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; else BRANCH=$TRAVIS_BRANCH; fi
  - ng build --prod
  - tar -czf dist.tar.gz dist
  - scp -o StrictHostKeyChecking=no -i ~/.ssh/geekhub-deployment dist.tar.gz deploy@104.248.253.61:~/theatre-front
  - ssh deploy@104.248.253.61 "rm -rf ~/theatre-front/$BRANCH && mkdir ~/theatre-front/$BRANCH"
  - ssh deploy@104.248.253.61 "tar -xf dist.tar.gz -C $BRANCH"

