language: node_js
node_js:
  - "10.15"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master
    - develop

before_script:
  - google-chrome --version
  - npm install -g @angular/cli
  - npm install webdriver-manager -g
  - webdriver-manager update
  - webdriver-manager start > ./webdriver.log 2>&1 &

script:
  - ng test --watch=false --browsers=ChromeHeadlessNoSandbox --code-coverage=true
#  - ng e2e

notifications:
  email:
    on_failure: change
    on_success: change

after_failure:
  - cat ./webdriver.log

after_script:
  - npm install ocular.js
  - $(npm bin)/ocular coverage/clover.xml
