language: node_js
node_js:
  - '10.15'
dist: xenial
addons:
  chrome: stable
  ssh_known_hosts: 104.248.253.61
  apt:
    packages:
      - sshpass

branches:
  only:
    - master
    - develop

script:
  - npm run lint
  - npm run lint-css
  - ng test --watch=false --browsers=ChromeHeadlessNoSandbox --code-coverage=true
  - ng e2e
  - if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then BRANCH=$TRAVIS_BRANCH; else BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; fi
  - if [ "$BRANCH" = "master" ]; then DOMAIN="https://theatre-shevchenko.ck.ua"; else DOMAIN="http://develop.theatre.pp.ua/$BRANCH"; fi
  - if [ "$BRANCH" = "master" ]; then ENV="production"; else ENV="staging"; fi
  - if [ "$BRANCH" = "master" ]; then BASE_HREF="/"; else BASE_HREF="/$BRANCH/"; fi
  - ng build -c "$ENV"-uk && ng run theatre-front:server:"$ENV"-uk
  - mv dist/theatre-front/browser/uk dist/browser_uk
  - mv dist/theatre-front/server/uk dist/server_uk
  - ng build -c "$ENV"-en && ng run theatre-front:server:"$ENV"-en
  - mv dist/browser_uk dist/theatre-front/browser/uk
  - mv dist/server_uk dist/theatre-front/server/uk

notifications:
  email:
    on_failure: change
    on_success: change

after_failure:
  - cat ./webdriver.log

after_script:
  - npm install ocular.js
  - "$(npm bin)/ocular coverage/clover.xml"

after_success:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - openssl aes-256-cbc -K $encrypted_40387a6d5956_key -iv $encrypted_40387a6d5956_iv -in deploy/key.enc -out ./deployment -d
  - mv deployment ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
  - ssh deploybot@104.248.253.61 "pwd"

  - cp ./deploy/branch.conf ./dist/
  - cp ./deploy/index.html ./dist/
  - cd dist/ && tar -zcvf ../dist.tar.gz * && cd -
  - scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa dist.tar.gz deploybot@104.248.253.61:~/theatre-front/$BRANCH.tar.gz
  - ssh deploybot@104.248.253.61 "rm -rf ~/theatre-front/$BRANCH && mkdir ~/theatre-front/$BRANCH"
  - ssh deploybot@104.248.253.61 "tar -xf ~/theatre-front/$BRANCH.tar.gz -C ~/theatre-front/$BRANCH"
  - ssh deploybot@104.248.253.61 "sed -e 's/{{branch}}/$BRANCH/g' ~/theatre-front/$BRANCH/branch.conf > ~/nginxconf/$BRANCH.conf"
  - echo "Deployed to $DOMAIN"

