language: node_js
node_js:
  - "6.9"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

before_script:
  - google-chrome --version
  - npm install -g @angular/cli
  - npm install webdriver-manager -g
  - webdriver-manager update
  - webdriver-manager start > ./webdriver.log 2>&1 &
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ng build --prod
  - ng test --watch=false --browser=ChromeHeadlessNoSandbox --code-coverage=true
  - ng e2e

notifications:
  email:
    on_failure: change
    on_success: change

after_failure:
  - cat ./webdriver.log

after_script:
  - cat coverage/clover.xml
  - npm install ocular.js
  - $(npm bin)/ocular coverage/clover.xml
