language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ng build --prod
  - ng test --watch=false

notifications:
  email:
    on_failure: change
    on_success: change
